### ISSUE TITLE
Settings/Rules sync

### ISSUE THREAD

**Issue by clairernovotny** [spectresystems/ghostly#33]
Is there a way to sync rules between computers? I don't see an import/export either.

One idea could be to use a special gist on GitHub with the rules and the client can check/update it as needed.

**Comment by patriksvensson** [comment]
@onovotny Great idea!

I have plans of implementing synchronization of categories, filters and rules. This will however require more permissions from the user (both read and write) so I'm currently pondering about how this is best implemented.

Anyway, it's on the radar. Thank you for creating this issue.

**Comment by patriksvensson** [comment]
@clairernovotny This feature has been implemented in version `1.10.0` and will be available in a couple of hours in the [Microsoft Store](https://www.microsoft.com/store/apps/9N5MVRB0XC60?cid=storebadge&ocid=badge).  
Thank you for suggesting this! 👍 

https://spectresystems.se/ghostly/docs/release-notes
