### ISSUE TITLE
Open issue on GitHub

### ISSUE THREAD

**Issue by onovotny** [spectresystems/ghostly#34]
It seems hard to get to the issue on GitHub if more actions are needed. Perhaps more ui elements could be hyperlinks back to the site? Or an icon, button, right-click command for "open on GitHub"?

**Comment by patriksvensson** [comment]
@onovotny You can double click the item in the notification list to go to the item on github, but I could also add a more explicit link as well to open the item. Perhaps an icon or hyperlink as you suggest.

**Comment by patriksvensson** [comment]
@onovotny This feature have been implemented and will appear in version `1.0.6` of Ghostly.
