### ISSUE TITLE
"Archive All" button

### ISSUE THREAD

**Issue by daveaglick** [spectresystems/ghostly#35]
After not opening Ghostly for a couple weeks I had a bunch of stuff in my Inbox. I imagine first use for a lot of people goes the same way. An "Archive All" button that moves everything in the Inbox to the Archive (including making subsequent API calls as needed) would be helpful in these scenarios. That would let you start from a blank state at that point in time.

**Comment by patriksvensson** [comment]
Perhaps a danger-zone (not the Kenny Loggins' song) button in `Settings->Notifications` where you can chose to archive all items?

**Comment by patriksvensson** [comment]
@daveaglick This have been added in version 1.0.5 of Ghostly which should be available soon in Microsoft Store.
