### ISSUE TITLE
"Mark All As Read" button

### ISSUE THREAD

**Issue by daveaglick** [spectresystems/ghostly#38]
Another request to help clean the slate - a "Mark All As Read" button would be helpful for both the Inbox and the Archive. For that matter, probably every category could benefit from such a button.

**Comment by patriksvensson** [comment]
Perhaps as a new menu item when you right click on a category?

**Comment by mkevenaar** [comment]
@daveaglick when you select multiple issues (or all with CTRL+A) you'll get an button on top to mark all items as read.

**Comment by daveaglick** [comment]
@mkevenaar that works great if you’re just trying to clear a single batch worth of items - the problem is when you have more unread issues than the query window size or some unread issues are outside the current window. Then you have to mark them in batches so a single button that marks them all at once would be helpful.

**Comment by patriksvensson** [comment]
@daveaglick This have been added in version 1.0.5 of Ghostly which should be available soon in Microsoft Store.
