### ISSUE TITLE
Issues Not Synchronizing

### ISSUE THREAD

**Issue by daveaglick** [spectresystems/ghostly#39]
I've noticed some odd behavior with issue downloading. See the screen shot below - two new Ghostly issues have come in but they're not showing up in my Inbox (which is empty) or my Archive (which I wouldn't expect since I didn't move them there, but checked just in case). Clicking the reload button doesn't appear to help. Maybe a rate limit issue?

![2019-08-15_08h31_11](https://user-images.githubusercontent.com/1020407/63094857-895a1700-bf37-11e9-8945-d84a82e4f141.png)

If it is a rate limit problem - a warning that your account is currently rate limited and that Ghostly will keep trying to sync might be good? Or a little banner across the top or bottom indicating you're currently in "rate limit mode"?

**Comment by nul800sebastiaan** [comment]
Could be related to #37 and #36.

**Comment by patriksvensson** [comment]
@daveaglick Thanks for reporting this issue.

Currently Ghostly only synchronize incoming notifications (and you don't receive notifications for things you've created yourself unless someone comments on them). There are plans for the next release (which I've written more about in #37) to add support for updating whole repositories (and keeping them in sync).

Don't be discouraged though! What you're seeing though is something that is in the backlog, and that is to take the user's actions into account (that doesn't generate notifications) and update these work items as part of synchronization.

I hope this answers your concerns.

**Comment by daveaglick** [comment]
That makes sense for the issue I opened up given that GitHub also doesn't create notifications for your own issues. But I'm also still missing #37 - it doesn't show up in my Inbox or Archive. Given that I'm watching the Ghostly repo, I would have expected that to generate a notification (and it looks like it did from the GitHub notification interface).

**Comment by patriksvensson** [comment]
@daveaglick If you go to `Search` in the navigation menu and write `id=37` can you still not see anything? If not, I'll open a bug for this.

**Comment by daveaglick** [comment]
Nope - the one result was a 37 from a different repo (which is good because it does show search is working, I just didn't get the notification item for Ghostly 37).

![2019-08-15_12h58_40](https://user-images.githubusercontent.com/1020407/63111775-6aba4700-bf5c-11e9-99fd-92495224d2ac.png)

**Comment by daveaglick** [comment]
I also just received the notification for #40 in the Inbox so it doesn't look like a rate limit problem. Maybe something with synchronization...

**Comment by patriksvensson** [comment]
@daveaglick Will take a look at it then!

**Comment by patriksvensson** [comment]
@daveaglick This should have been fixed in `1.0.4`. Reopen this issue if the problem persists.
