### ISSUE TITLE
Emoji in labels not parsed

### ISSUE THREAD

**Issue by mkevenaar** [spectresystems/ghostly#42]
When a label contains an emoji the emoji is not parsed:

https://github.com/mkevenaar/chocolatey-coreteampackages/pull/181

![image](https://user-images.githubusercontent.com/834643/63230698-a7ae6400-c210-11e9-9069-f16d104729ad.png)

**Comment by patriksvensson** [comment]
@mkevenaar Thanks for reporting this!

**Comment by patriksvensson** [comment]
@mkevenaar This have been added in version 1.0.5 of Ghostly which should be available soon in Microsoft Store.

The fix will be applied once a notification with the label is updated.

**Comment by mkevenaar** [comment]
@patriksvensson Should it also be fixed when a new issue/PR is created using a label with an emoji?

According to the about page, I am on 1.0.5.0, but with a new PR I still have the same issue: https://github.com/mkevenaar/chocolatey-coreteampackages/pull/197

**Comment by mkevenaar** [comment]
@patriksvensson your update in https://github.com/spectresystems/ghostly/issues/46 did not parse the :+1: emoji.

**Comment by patriksvensson** [comment]
@mkevenaar Hmm, here it does. Perhaps the label haven't been updated yet. Will add a migration step to next release that will migrate all labels that haven't been updated.

![image](https://user-images.githubusercontent.com/357872/64069482-4ba10200-cc4a-11e9-9983-6c6042627f4b.png)
