### ISSUE TITLE
Link to filters inside dialog

### ISSUE THREAD

**Issue by mkevenaar** [spectresystems/ghostly#46]
It would be nice to add a link to the documentation regarding filters inside the `New Category`. Just like is available inside the `New Rule` dialog

**Comment by patriksvensson** [comment]
@mkevenaar There is a link to the docs, but the `This is a filter` checkbox must be checked for it to appear (see image).

Perhaps this should be changed so it's always showing?

![image](https://user-images.githubusercontent.com/357872/63771972-70a71500-c8d8-11e9-8b7b-d1a953ec82b7.png)

**Comment by mkevenaar** [comment]
@patriksvensson That would make it a bit nicer, yes. It will also stop the dialog from resizing.

**Comment by patriksvensson** [comment]
@mkevenaar This was resolved in version 1.1.2
