### ISSUE TITLE
Run only one rule

### ISSUE THREAD

**Issue by mkevenaar** [spectresystems/ghostly#48]
**Is your feature request related to a problem? Please describe.**
I would love to be able to run only one rule, and not all

**Describe the solution you'd like**
Add an extra button at the end of the rule, with the play button. This should open the dialog "Run rule for category" and then only the selected rule will be applied to that category.

**Comment by patriksvensson** [comment]
@mkevenaar I can see how that would be useful. Added this to 1.0.7 milestone. Thanks for the suggestion 👍

**Comment by patriksvensson** [comment]
This feature have been implemented and will appear in version 1.1.2.
