### ISSUE TITLE
Difficult to read non-profit details while synchronizing

### ISSUE THREAD

**Issue by sharwell** [spectresystems/ghostly#53]
**Ghostly version**

1.0.6

**Windows 10 version**

1903

**Describe the bug**

The charities and non-profit details are difficult to read while synchronizing.

**To Reproduce**

1. Start synchronization as a new user
2. Visit the Purchase page

**Expected behavior**
Can read the text (see screenshot)

**Screenshots** (optional)

![image](https://user-images.githubusercontent.com/1408396/64283325-14fa0e80-cf0c-11e9-9625-8224f7ba4af4.png)

**Additional context** (optional)

**Comment by patriksvensson** [comment]
@sharwell You're absolutely right. Should be fixed in the next version.

Thank you fore reporting this 👍

**Comment by patriksvensson** [comment]
@sharwell This bug has been fixed in version `1.10.0` and will be available in a couple of hours in the [Microsoft Store](https://www.microsoft.com/store/apps/9N5MVRB0XC60?cid=storebadge&ocid=badge).  
Thank you for reporting this! 👍 

https://spectresystems.se/ghostly/docs/release-notes
