### ISSUE TITLE
Synchronization progress bar

### ISSUE THREAD

**Issue by sharwell** [spectresystems/ghostly#54]
**Is your feature request related to a problem? Please describe.**

It's difficult to tell how long synchronization will take, and whether or not it's progressing.

**Describe the solution you'd like**

It would be nice to see the synchronization progress as a percentage, or some other indication of the work to complete.

**Describe alternatives you've considered** (optional)

n/a

**Additional context** (optional)

n/a

**Comment by patriksvensson** [comment]
@sharwell Sounds like a good idea! Thanks for opening this issue 👍

**Comment by patriksvensson** [comment]
This feature has been implemented in version `1.11.0` and will be available in a couple of hours in the Microsoft Store.
Thank you for suggesting this! 👍

https://spectresystems.se/ghostly/docs/release-notes
