### ISSUE TITLE
Tool tip does not show title on hover

### ISSUE THREAD

**Issue by sharwell** [spectresystems/ghostly#56]
**Ghostly version**

1.0.6

**Windows 10 version**

1903

**Describe the bug**

When hovering over a truncated title in the inbox, the full title is not shown. Instead, a tool tip appears showing `Ctrl+F`.

**To Reproduce**

1. Go to the inbox
2. Hover over a truncated title (ending with `...`)

**Expected behavior**

A tool tip appears showing the full title.

**Screenshots** (optional)

![image](https://user-images.githubusercontent.com/1408396/64287117-b89aed00-cf13-11e9-9d81-69b87baefe8b.png)

**Additional context** (optional)

n/a

**Comment by patriksvensson** [comment]
@sharwell This is a bug in UWP WinUI (see [this issue](https://github.com/Microsoft/microsoft-ui-xaml/issues/8)) that I thought I had worked around, but it seems like I need to revisit this again.

Thank you for reporting this, much appreciated 👍

**Comment by patriksvensson** [comment]
This bug have been fixed and will appear in version 1.1.2.
