### ISSUE TITLE
Quick refresh of an issue

### ISSUE THREAD

**Issue by sharwell** [spectresystems/ghostly#58]
**Is your feature request related to a problem? Please describe.**

Refreshing takes a _very_ long time, to the point that it is not a usable operation when executed explicitly.

**Describe the solution you'd like**

I would like to be able to refresh the right hand pane (see screenshot) without triggering a refresh of anything else.

![image](https://user-images.githubusercontent.com/1408396/64378005-91f6b800-cfe0-11e9-8c7e-263b57f72117.png)

**Describe alternatives you've considered** (optional)

n/a

**Additional context** (optional)

n/a

**Comment by patriksvensson** [comment]
@sharwell This was implemented in Ghostly 1.9.0
