### ISSUE TITLE
Completion for query language

### ISSUE THREAD

**Issue by mholo65** [spectresystems/ghostly#62]
**Is your feature request related to a problem? Please describe.**
I always seem to forget the syntax for the query language, completion would be nice.

**Describe the solution you'd like**
Completion for query syntax

**Describe alternatives you've considered** (optional)
RTFM 🤔 and learn syntax

**Additional context** (optional)

**Comment by patriksvensson** [comment]
Will take a look at this once all currently known bugs are fixed.

**Comment by patriksvensson** [comment]
@mholo65 This feature is now available in version 1.3.3.
