### ISSUE TITLE
Purchase buttons does not have correct text

### ISSUE THREAD

**Issue by mgnslndh** [spectresystems/ghostly#67]
**Ghostly version**
1.3.3

**Windows 10 version**
1903

**Describe the bug**

The text on the purchase buttons does not seem to be correct.

![image](https://user-images.githubusercontent.com/1139118/68072316-afe45d00-fd84-11e9-80be-6031716c5955.png)

**To Reproduce**

I just installed, launched and clicked the Purchase button.

**Expected behavior**
Purchase buttons should have readable text in english.

**Additional context** (optional)

Windows 10 in English UI with Swedish culture settings.

**Comment by patriksvensson** [comment]
@mgnslndh Thanks for reporting this! Will make sure it's fixed in the next version!

**Comment by patriksvensson** [comment]
Fixed in 1.4.0 (available tomorrow)
