### ISSUE TITLE
Scrollbar over icons

### ISSUE THREAD

**Issue by mkevenaar** [spectresystems/ghostly#71]
**Ghostly version**
1.7.0

**Windows 10 version**
1909 (patched with currently all the latest updates)

_Please include the OS build number if you're running an insider build of Windows 10)_

**Describe the bug**
On a normal PC without touch, when you move your mouse over to the "Mark as read" button, the scrollbar comes out and is partially over the buttons on the right.

**To Reproduce**
1. Make sure your list has enough items that a scrollbar is required
2. Move your mouse to the right of an item
3. Notice the scrollbar on the right (see image below)

**Expected behavior**
The icons to be accessible or the scrollbar not to pop out.

**Screenshots**
![image](https://user-images.githubusercontent.com/834643/82640453-e98a9180-9c0a-11ea-8424-53e75f461431.png)

**Comment by patriksvensson** [comment]
@mkevenaar Great catch! I haven't noticed that myself. Will fix in next version! :+1:
Thanks!

**Comment by patriksvensson** [comment]
This bug has been fixed in version `1.9.0` and will be available in a couple of hours in the [Microsoft Store](https://www.microsoft.com/store/apps/9N5MVRB0XC60?cid=storebadge&ocid=badge).  
Thank you for reporting this! 👍 

https://spectresystems.se/ghostly/docs/release-notes
