### ISSUE TITLE
Syntax Error when adding repo with a dot in it's in name. 

### ISSUE THREAD

**Issue by MikeCodesDotNET** [spectresystems/ghostly#72]
**Ghostly version**
1.8.0 (x64)

**Windows 10 version**
2004 - Build 19640.1

**Describe the bug**
Syntax error when attempting to add repository with a '.' character in it's name. 

**To Reproduce**
1. Create a filter with the following "repro=xamarinn.forms". 

**Expected behavior**
I would expect that should either add the repro correctly or inform the user to surround the repro name with quotation marks as its a string.

**Comment by patriksvensson** [comment]
@MikeCodesDotNET Thanks for reporting this.

Just a question, there is no query property called "repro" in Ghostly, did you mean `repo`?

**Comment by MikeCodesDotNET** [comment]
Yep, I meant to say repo.  Apologies for any confusion! 

FYI, I love the app. Already signed up for the pro account!

**Comment by patriksvensson** [comment]
This bug has been fixed in version `1.9.0` and will be available in a couple of hours in the [Microsoft Store](https://www.microsoft.com/store/apps/9N5MVRB0XC60?cid=storebadge&ocid=badge).  
Thank you for reporting this! 👍 

https://spectresystems.se/ghostly/docs/release-notes
