### ISSUE TITLE
Release notes has too many 2020 dates

### ISSUE THREAD

**Issue by ErikEJ** [spectresystems/ghostly#73]
**Ghostly version**
i.e. 1.0.5

**Windows 10 version**
i.e. 1903

_Please include the OS build number if you're running an insider build of Windows 10)_

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots** (optional)

**Additional context** (optional)

**Comment by patriksvensson** [comment]
@ErikEJ Good catch, will fix that! Thanks!

**Comment by patriksvensson** [comment]
Fixed!
