### ISSUE TITLE
Right click on filter, mark all as read

### ISSUE THREAD

**Issue by mkevenaar** [spectresystems/ghostly#74]
**Is your feature request related to a problem? Please describe.**
I would like to be able to "mark as read" from a filter.

**Describe the solution you'd like**
Next to "Edit filter" and "Delete filter" I would like to have an "Mark all as read"

**Describe alternatives you've considered** (optional)
N/A

**Additional context** (optional)

**Comment by patriksvensson** [comment]
@mkevenaar Great idea! I’ve been thinking about this as well so I’ll make sure to add it in the next version 👍

**Comment by patriksvensson** [comment]
This feature has been implemented in version 1.9.0 and will be available in a couple of hours in the [Microsoft Store](https://www.microsoft.com/store/apps/9N5MVRB0XC60?cid=storebadge&ocid=badge).  
Thank you for suggesting this! 👍 

https://spectresystems.se/ghostly/docs/release-notes
