### ISSUE TITLE
Action to copy link to issue/PR

### ISSUE THREAD

**Issue by agc93** [spectresystems/ghostly#78]
**Is your feature request related to a problem? Please describe.**
Currently if I want to link someone to an issue I'm looking at in Ghostly, I need to open in Browser, then copy the URL out of my address bar to share.

**Describe the solution you'd like**
The simplest approach (as far as I can see) would be adding a "copy link" action in either the list context menu or the action buttons in the right pane, that would copy the URL for the issue/PR/tag/whatever to the clipboard.

**Describe alternatives you've considered** (optional)
I mean, it *could* be part of a more complex "Share" menu but for my purposes, copying the URL would cover 99% of use cases.

**Comment by patriksvensson** [comment]
@agc93 Excellent idea! 👍

**Comment by mkevenaar** [comment]
Implementing this will also give an user the possibility to open an issue in another (not default) browser or instance.

**Comment by patriksvensson** [comment]
@gep13 @mkevenaar Is it something like this you're asking for?

![sharing](https://user-images.githubusercontent.com/357872/88485337-6886a800-cf75-11ea-8faf-67cbf262eaea.gif)

**Comment by mkevenaar** [comment]
@patriksvensson LGTM! :shipit:

**Comment by patriksvensson** [comment]
@mkevenaar Found an emoji bug 😁

![image](https://user-images.githubusercontent.com/357872/88488838-641bb880-cf90-11ea-872d-cc9cc42fe76e.png)

**Comment by agc93** [comment]
@patriksvensson Also looks good to me :shipit: (and I'll even forgive you for getting Gary and I confused 😆 )

**Comment by patriksvensson** [comment]
@agc93 This feature has been implemented in version 1.12.0 and will be available in a couple of hours in the [Microsoft Store](https://www.microsoft.com/store/apps/9N5MVRB0XC60?cid=storebadge&ocid=badge).  
Thank you for suggesting this! 👍 

https://spectresystems.se/ghostly/docs/release-notes

**Comment by mkevenaar** [comment]
@patriksvensson thank you for implementing this, it works like a charm! 🚀
