### ISSUE TITLE
All items are marked as "draft"

### ISSUE THREAD

**Issue by mkevenaar** [spectresystems/ghostly#79]
**Ghostly version**
i.e. 1.11.0 (x64)

**Windows 10 version**
2004

**Describe the bug**
All synced items are marked as "Draft"

**To Reproduce**
Just sync.

**Expected behavior**
Not marked as Draft

**Screenshots** (optional)
![image](https://user-images.githubusercontent.com/834643/89826607-c9f26d80-db56-11ea-8320-164a57b269eb.png)

**Comment by patriksvensson** [comment]
@mkevenaar I hadn't noticed! Will fix this in 1.12.0 😀

**Comment by patriksvensson** [comment]
This bug has been fixed in version 1.12.0 and will be available in a couple of hours in the [Microsoft Store](https://www.microsoft.com/store/apps/9N5MVRB0XC60?cid=storebadge&ocid=badge).  
Thank you for reporting this! 👍

https://spectresystems.se/ghostly/docs/release-notes
