### ISSUE TITLE
Allow customizing key bindings

### ISSUE THREAD

**Issue by loic-sharma** [spectresystems/ghostly#80]
**Is your feature request related to a problem? Please describe.**
I'd like to mark items in my inbox as read using the control+Q key binding (this matches Outlook).

**Describe the solution you'd like**
I'd like to add custom key bindings for common actions.

**Comment by patriksvensson** [comment]
@loic-sharma Great suggestion. I'll add something in the next version. Perhaps I'll just hardcode the key combinations for now while figuring out how it should work.

**Comment by patriksvensson** [comment]
@loic-sharma I've added support for `CTRL+Q` shortcut in version `1.13.0` and will be available in a couple of hours in the [Microsoft Store](https://www.microsoft.com/store/apps/9N5MVRB0XC60?cid=storebadge&ocid=badge).

Thank you for suggesting this! 👍

https://spectresystems.se/ghostly/docs/release-notes
